### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CanerKaraca23** [opa334/libundirect#1]
After updating libundirect to 1.1, springboard crashed and crashlog says it's because of EmojiPort i think.

CrashLog: https://controlc.com/00f61191

https://cdn.discordapp.com/attachments/570634688813858820/820301565209608233/image0.png

iPhone 5S, iOS 12.5.1, Chimera

**Comment by opa334** [comment]
EmojiAttributes needs to be updated support libundirect 1.1
