### ISSUE TITLE
Support for sandboxed app

### ISSUE THREAD

**Issue by yur1xpp** [opa334/libundirect#3]
If I'm not mistaken, this won't work with sandboxed app right? If so, do you have any plan on making this partially compatible with app, this is especially useful for the `libundirect_find` function.

Thanks.

**Comment by opa334** [comment]
this works fine for all processes running on a jailbroken device. if you intend to inject a dylib into a sideloaded application on a jailed device then it will still work but hooking the direct method will not work (because it is impossible to hook C functions in sideloaded applications).
